androidTest: simple test for Preview and Surface usage
android/camera-samples pull request #306
Opened 2020-09-22 03:09 UTC by luncliff

### Changes

It was a bit hard for me to try CameraX with the sample code. The PR adds a new test class which is shorter than the CameraFragment.kt.
 
### Coverage?

Tested with...

* Sony G8141, OS 9.0

2020-09-22 23:34 UTC, owahltinez commented
Hi @luncliff thanks for this PR! We don't have any other code in Java for this sample, do you mind converting it to Kotlin? That way we can have a consistent codebase.

2020-09-23 01:50 UTC, luncliff commented
@owahltinez thanks for the comment! 
Since I don't know Kotlin, so reformed the code with Android Studio. 

Any kind of review(especially for _readability_) will be helpful :)

2020-10-01 15:16 UTC, owahltinez requested changes
Thanks for converting this to Kotlin! I have a few suggestions to make this code more idiomatic

2020-10-01 15:16 UTC, owahltinez commented on CameraXBasic/app/src/androidTest/java/com/android/example/cameraxbasic/CameraPreviewTest.kt
> +        registry!!.markState(Lifecycle.State.DESTROYED)
Replace with `registry?.markState(...)`

2020-10-01 15:16 UTC, owahltinez commented on CameraXBasic/app/src/androidTest/java/com/android/example/cameraxbasic/CameraPreviewTest.kt
> +    }
Can be simplified to:

```
override fun getLifecycle() = registry
```

2020-10-05 01:36 UTC, luncliff commented on CameraXBasic/app/src/androidTest/java/com/android/example/cameraxbasic/CameraPreviewTest.kt
> +    private var count = AtomicInteger(0)
Thanks for the point. 

`camera` is moved into the `@Test`

IMO placing `onImageAvailable` to test class's method is clear and simple. But it restricts `reader `and `count` to be member variable.

2020-10-17 23:49 UTC, owahltinez commented
Thank you! I think it looks good. Can you please confirm that the test runs successfully?

2020-10-17 23:50 UTC, owahltinez commented
Also it looks like you need to rebase with the main branch before we can merge it.

2020-10-19 00:24 UTC, luncliff commented
> Also it looks like you need to rebase with the main branch before we can merge it.

Great! I already rebased with main in the 68d8a0f, and with my device the `connectedAndroidTest` runs well.

2020-11-08 19:10 UTC, owahltinez commented
I'm still seeing "This branch cannot be rebased due to conflicts"

2020-11-09 07:22 UTC, luncliff commented
@owahltinez Sorry. I confused between `rebase` and `merge`. I just pushed after `git rebase main`. Did it work well?

2020-11-24 17:26 UTC, owahltinez commented
Much better now, thank you!

2020-11-24 17:27 UTC, owahltinez approved these changes

2020-11-24 17:27 UTC, merged