Update gradle and other dependencies for CameraX samples.
android/camera-samples pull request #507
Opened 2022-09-08 17:44 UTC by donovanfm

All changes are from running Upgrade Assistant suggestions, with the exception of updating TensorFlow Lite dependencies in CameraXAdvanced which was manual.

2022-09-13 16:29 UTC, madebymozart approved these changes
LGTM!

2022-09-13 16:34 UTC, merged

2025-03-12 20:13 UTC, Stan4402 requested changes

2025-03-12 20:13 UTC, Stan4402 commented on CameraXBasic/build.gradle
> +        classpath 'com.android.tools.build:gradle:7.2.2'
com.android.tools.build:gradle:7.2.2'

2025-03-12 20:13 UTC, Stan4402 commented on CameraXAdvanced/tflite/build.gradle
> +    implementation 'org.tensorflow:tensorflow-lite-support:0.4.2'
'org.tensorflow:tensorflow-lite-support:0.4.2'

2025-03-12 20:13 UTC, Stan4402 commented on CameraXAdvanced/tflite/build.gradle
> +    implementation 'org.tensorflow:tensorflow-lite-gpu:2.9.0'
'org.tensorflow:tensorflow-lite-gpu:2.9.0'

2025-03-12 20:13 UTC, Stan4402 commented on CameraXAdvanced/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip

2025-03-12 20:13 UTC, Stan4402 commented on CameraXBasic/build.gradle
> +        classpath 'com.android.tools.build:gradle:7.2.2'
'com.android.tools.build:gradle:7.2.2'

2025-03-12 20:13 UTC, Stan4402 commented on CameraXAdvanced/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip
+6

2025-03-12 20:13 UTC, Stan4402 commented on CameraXAdvanced/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip